RootSM:
    HomeScreen:
        name: "home"
    BossesScreen:
        name: "bosses"
    BoostedScreen:
        name: "boosted"
    TrainingScreen:
        name: "training"
    ImbuementsScreen:
        name: "imbuements"
    HuntScreen:
        name: "hunt"
    StaminaScreen:
        name: "stamina"
    SettingsScreen:
        name: "settings"
    BossFavoritesScreen:
        name: "boss_favorites"


